/* 
// kingdom attributes:
// culture (0, 100)
// economy (0, 100)
// military (0, 100)
// technology (0, 100),
// government ('r' = republic, 'c' = communist, 't' = tribal, 'a' = anarchy, 'k' = kingdom/royalty),
// education (0, 100)
// religion (0, 100)
// farming (0, 100)
// diplomacy (0, 100) (0 = hostile, 100 = peaceful)
// artistry (0, 100)
// crafting (0, 100)
*/
names.kingdoms = [
    {values:[
        {value:'ab', government:'t'},
        {value:'aben', government:'k'},
        {value:'ac', government:'k'},
        {value:'adr', government:'k'},
        {value:'al', government:'r'},
        {value:'am', government:'r'},
        {value:'as', government:'k'},
        {value:'bael', government:'k'},
        {value:'bal', government:'c'},
        {value:'bar', government:'r'},
        {value:'bed', government:'c'},
        {value:'bel', government:'r'},
        {value:'bik', government:'t'},
        {value:'bin', government:'r'},
        {value:'bis', government:'k'},
        {value:'bor', government:'c'},
        {value:'bri', government:'r'},
        {value:'cam', government:'k'},
        {value:'can', government:'k'},
        {value:'cas', government:'r'},
        {value:'casp', government:'r'},
        {value:'chi', government:'c'},
        {value:'daes', government:'k'},
        {value:'div', government:'r'},
        {value:'dwar', government:'k'},
        {value:'elv', government:'r'},
        {value:'es', government:'r'},
        {value:'eth', government:'k'},
        {value:'eva', government:'r'},
        {value:'evan', government:'k'},
        {value:'ever', government:'c'},
        {value:'fan', government:'r'},
        {value:'far', government:'r'},
        {value:'fay', government:'k'},
        {value:'fel', government:'k'},
        {value:'fon', government:'c'},
        {value:'fut', government:'r'},
        {value:'ga', government:'t'},
        {value:'gen', government:'c'},
        {value:'gha', government:'c'},
        {value:'gor', government:'k'},
        {value:'hel', government:'k'},
        {value:'hest', government:'r'},
        {value:'hon', government:'c'},
        {value:'ik', government:'k'},
        {value:'il', government:'r'},
        {value:'ind', government:'k'},
        {value:'ish', government:'t'},
        {value:'ist', government:'c'},
        {value:'ing', government:'r'},
        {value:'kri', government:'r'},
        {value:'kur', government:'t'},
        {value:'ky', government:'t'},
        {value:'nar', government:'r'},
        {value:'nida', government:'t'},
        {value:'pen', government:'r'},
        {value:'phe', government:'r'},
        {value:'pun', government:'c'},
        {value:'que', government:'r'},
        {value:'qui', government:'c'},
        {value:'rus', government:'c'},
        {value:'run', government:'r'},
        {value:'ta', government:'k'},
        {value:'tar', government:'t'},
        {value:'tre', government:'r'},
        {value:'tri', government:'k'},
        {value:'tsu', government:'k'},
        {value:'ult', government:'c'},
        {value:'ut', government:'c'},
        {value:'zel', government:'t'},
        {value:'zem', government:'t'},
        {value:'zo', government:'c'},
        {value:'zu', government:'t'}
    ]},
    {canSkip:true, skipChance:2, values:[
        {value:'al'},
        {value:'ar'},
        {value:'bos', government:'t'},
        {value:'cha'},
        {value:'chi', government:'c'},
        {value:'din', government:'k'},
        {value:'do'},
        {value:'du', government:'t'},
        {value:'el'},
        {value:'elum', government:'k'},
        {value:'elus', government:'k'},
        {value:'em'},
        {value:'emb'},
        {value:'en'},
        {value:'end'},
        {value:'er'},
        {value:'fel', government:'k'},
        {value:'ira'},
        {value:'sha'},
        {value:'shan', government:'c'},
        {value:'shi', government:'c'},
        {value:'olen', government:'r'},
        {value:'or'},
        {value:'win', government:'k'},
    ]},
    {canSkip:true, skipChance:10, values:[
        {value:'a'},
        {value:'ar'},
        {value:'ba'},
        {value:'bi'},
        {value:'ca', government:'r'},
        {value:'cia', government:'r'},
        {value:'ia', government:'k'},
        {value:'ira'},
        {value:'is'},
        {value:'gard', government:'k'},
        {value:'heim', government:'k'},
        {value:'helm', government:'k'},
        {value:'lor', government:'k'},
        {value:'mond', government:'k'},
        {value:'nia', government:'k'},
        {value:'tan', government:'r'},
        {value:'va'},
        {value:'via'},
        {value:'ya'}
    ]}
];